### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by sorokinvj** [RRutsche/react-parallax#68] opened 2019-12-24 18:04 UTC
hey guys!

So, I spend a couple of days building a landing page with react-parallax, and everything went fine, but when I deployed the bundle strange Error happened:

```
Uncaught TypeError: Super expression must either be null or a function
    at 5.9b604282.chunk.js:1
    at 5.9b604282.chunk.js:1
    at Module.<anonymous> (5.9b604282.chunk.js:1)
    at r (5.9b604282.chunk.js:1)
    at e.exports (5.9b604282.chunk.js:1)
    at Object.<anonymous> (5.9b604282.chunk.js:1)
    at s (localhost/:1)
    at Module.1141 (main.02f04cab.chunk.js:1)
    at s (localhost/:1)
    at Object.432 (main.02f04cab.chunk.js:1)
```
I don't know what causes the error, but I double checked everything – and it is certainly something with react-parallax lib, and doesn't really depends on OS – same thing is happening on my prod server (Ubuntu) and local machine (Mac OS) when I serve the bundle. In development mode everything is ok. 

The error happens when I use the basic example.

How to debug this further?

**Comment by rrutsche** [comment] 2019-12-26 23:26
Hi,
glad you use the package. 
Can you provide some more info about your system and/or setup? It is really hard for me to get an idea without more info. Are you using next.js, or do you bundle it with a custom webpack configuration? Such things would be very helpful. 
Maybe you can provide a minimal repo or a codesandbox setup (see description in readme)?
Thanks

**Comment by sorokinvj** [comment] 2019-12-28 16:01
Sure! 
I will do repo today later, in the meanwhile
this is my package.json
Its basically Create React App, React-Router with Apollo server

```
  "dependencies": {
    "@google-cloud/speech": "^3.2.3",
    "@google-cloud/storage": "^3.0.3",
    "@lingui/react": "^2.8.3",
    "amr-duration": "^0.2.0",
    "apollo-cache-inmemory": "^1.4.3",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.4.13",
    "apollo-link": "^1.2.11",
    "apollo-link-context": "^1.0.14",
    "apollo-link-error": "^1.1.10",
    "apollo-link-ws": "^1.0.17",
    "apollo-server": "^2.4.8",
    "apollo-server-express": "^2.4.2",
    "apollo-upload-client": "^11.0.0",
    "apollo-utilities": "^1.3.1",
    "aws-amplify": "^1.1.40",
    "aws-amplify-react": "^2.5.3",
    "babel-plugin-styled-components": "^1.10.0",
    "bcrypt": "^3.0.6",
    "body-parser": "^1.18.3",
    "concurrently": "latest",
    "cors": "latest",
    "dayjs": "^1.8.13",
    "dotenv": "^8.0.0",
    "draft-convert": "^2.1.4",
    "draft-js": "^0.11.0",
    "esm": "^3.2.22",
    "express": "latest",
    "ffmpeg-peaks": "^0.3.3",
    "fluent-ffmpeg": "^2.1.2",
    "graphql": "latest",
    "graphql-subscriptions": "^1.1.0",
    "graphql-tag": "^2.10.1",
    "graphql-tools": "latest",
    "graphql-type-json": "^0.3.0",
    "graphql-upload": "^8.0.4",
    "if-env": "^1.0.4",
    "immutable": "^4.0.0-rc.12",
    "jsdom": "^15.1.0",
    "jsonwebtoken": "^8.2.1",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.15",
    "mongoose": "^5.1.3",
    "mongoose-float": "^1.0.4",
    "music-metadata": "^4.2.1",
    "progress-stream": "^2.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.2",
    "react-apollo": "^2.4.1",
    "react-dom": "^16.8.2",
    "react-dropzone": "^10.1.5",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "latest",
    "react-scroll-parallax": "^2.2.0",
    "semantic-ui-react": "^0.88.1",
    "slate": "^0.47.4",
    "slate-react": "^0.22.4",
    "styled-components": "^4.1.3",
    "subscriptions-transport-ws": "^0.9.16",
    "wavesurfer.js": "^3.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@lingui/cli": "^2.8.3",
    "@lingui/loader": "^2.8.3",
    "@lingui/macro": "^2.8.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-plugin-dynamic-import-node": "^2.3.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.11.0",
    "nodemon": "^1.17.5",
    "prettier": "^1.19.1",
    "slate-prop-types": "^0.5.37"
  },
```

**Comment by sorokinvj** [comment] 2019-12-28 19:53
Here is the repo – https://github.com/sorokinvj/test-react-parallax

Just build it locally 
```
yarn build
```

and serve locally with 
```
serve -s build
```

**Comment by sienatra** [comment] 2020-01-03 02:22
I'm also having the same problem here using nextjs. Works perfectly in development mode, but spitting out an error when the production build is run.
<pre>TypeError: Super expression must either be null or a function
    at index.js:1
    at index.js:1
    at Object.Otrq.e.exports (index.js:1)
    at n (index.js:1)
    at Object.Otrq.e.exports (index.js:1)
    at n (index.js:1)
    at Otrq.e.exports (index.js:1)
    at Object.Otrq (index.js:1)
    at l (webpack-08f7b238829422e3b9b2.js:1)
    at Module.RNiq (index.js:1)</pre>

**Comment by rrutsche** [comment] 2020-01-03 17:03
Thanks for the repository link. I could reproduce it. I will also try it with a nextjs setup. Think it is due to an uglify/terser issue. Don‘t know which one cra and nextjs is using but I saw some issues on their repositories that look similar. 
I will investigate.

**Comment by rrutsche** [comment] 2020-01-03 22:02
So I found a solution. It was a `terser` plugin configuration issue. I added the `keep_fnames` option to prevent function/class names getting mangled during production builds. Fix is in version `3.0.3`.
I'm happy about a note if the solution works for you guys.

**Comment by sienatra** [comment] 2020-01-03 22:08
Updated to `3.0.3` and it seems to be working perfectly. Thanks!

**Comment by rrutsche** [comment] 2020-01-03 22:13
Closing the issue now. Feel free to reopen it if there is still related problems.

**Closed as completed by rrutsche** 2020-01-03 22:13 UTC

**Comment by sorokinvj** [comment] 2020-01-13 16:32
Thanks!!!! Works perfectly now and mobile is awesome!

**Comment by jaedanpersaud12** [comment] 2023-05-12 15:53
@rrutsche getting the same error in v3.5.1

`TypeError: Super expression must either be null or a function`

**Comment by philohelp** [comment] 2024-06-01 07:58
Same error here with nextjs 14. I tried to downgrade to 3.0.3 with no success.

**Comment by Sherlock92** [comment] 2025-01-30 17:12
Also still getting this error with nextjs 15 @rrutsche
