### ISSUE TITLE
White space when image is not high enough

### ISSUE THREAD

**Issue by Bram-Zijp** [RRutsche/react-parallax#26] opened 2017-03-13 08:52 UTC
When on small width screens many images show a white space before entering the parallax wrapper. Might be an idea to calculate extra width needed (on resize) so that there will always be enough height to work with.

**Comment by rrutsche** [comment] 2017-03-21 19:45
@Bram-Zijp Do you use the `Background` component or the `bgImage` prop? I thought I covered most of the cases. Can you give me a concrete example so I can check it. Maybe even a minimum working page or at least some values I can work with (image size, container size etc). Thanks

**Comment by rrutsche** [comment] 2017-04-20 07:27
@Bram-Zijp Is this issue still present? Could you give me some values/setup so I am able to reproduce it? At least browser and image dimensions would be good

**Comment by rrutsche** [comment] 2017-05-23 07:12
@Bram-Zijp I will close this issue for now as I cannot reproduce this with my images and settings. You can re-open it at any time when you have more detailed information about your setup so I can have a look at this.

**Closed as completed by rrutsche** 2017-05-23 07:12 UTC
