### ISSUE TITLE
Ref Owner Error

### ISSUE THREAD

**Issue by johnnaumann** [RRutsche/react-parallax#21] opened 2016-12-29 17:38 UTC
![screen shot 2016-12-29 at 17 37 46](https://cloud.githubusercontent.com/assets/3016847/21549911/91f1a7f4-cded-11e6-8431-e0c7c908fa7d.png)

I get this error when using when using React 15.3.2.

**Comment by rrutsche** [comment] 2016-12-30 10:11
@JohnPett Thanks for your feedback. I tried to reproduce this error but unfortunately I can't. 
I just cloned a react boilerplate, explicitly installed react 15.3.2 and used the latest Parallax version [1.2.2](https://github.com/RRutsche/react-parallax/releases/tag/v1.2.2).
(npm version = 3.10.9, node version = v6.9.2)
Do you have an example project where this is happening?

**Comment by rrutsche** [comment] 2017-01-09 22:58
@JohnPett Is this issue still present? I could not reproduce it.

**Comment by johnnaumann** [comment] 2017-01-10 10:01
@RRutsche – I have used a different boilerplate, so the error still exists for me, but maybe something that I have done, I guess.

**Comment by rrutsche** [comment] 2017-01-15 21:32
@JohnPett Ok, I will close the issue for now. Just let me know if you have the impression that it's still an issue with the package itself.

**Closed as completed by rrutsche** 2017-01-15 21:32 UTC
